name: Sync Fork with Upstream
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [sync]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Sync with Upstream
        run: |
          git remote add upstream <original-repo>
          git fetch upstream
          git checkout <branch-name>
          git merge upstream/<branch-name> --no-edit
          git push origin <branch-name>
